package algonquin.cst2335.finalproject.ui;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import algonquin.cst2335.finalproject.databinding.ActivityMainBinding;

/**
 * The MainActivity class represents the main entry point of the application.
 * It inflates the layout, sets up UI elements, and handles button click events to navigate to other activities.
 * @author Jay Pyefinch
 */
public class MainActivity extends AppCompatActivity {

    /**
     * The binding object for the main activity layout, {@link MainActivity}.
     * This class is generated by data binding and provides direct access to the views within the layout.
     */
    ActivityMainBinding binding;

    /**
     * Called when the activity is first created. This is where UI initialization and event setup occur.
     *
     * @param savedInstanceState The saved instance state bundle, containing previous state information.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityMainBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        binding.flightTrackerButton.setOnClickListener( v -> {
            Intent airTracker = new Intent(MainActivity.this, AirportDisplayBoardActivity.class);
            MainActivity.this.startActivity(airTracker);
        });

        binding.bearButton.setOnClickListener( v -> {
            Intent bear = new Intent(MainActivity.this, BearGeneratorActivity.class);
            MainActivity.this.startActivity(bear);
        });

        binding.currencyExchangeButton.setOnClickListener( v -> {
            Intent currencyConverter = new Intent(MainActivity.this, CurrencyActivity.class);
            MainActivity.this.startActivity(currencyConverter);
        });

        binding.triviaButton.setOnClickListener( v -> {
            Intent trivia = new Intent(MainActivity.this, TriviaActivity.class);
            MainActivity.this.startActivity(trivia);
        });

    }
}